const Country = {
  USA: "Spojené státy americké",
  Canada: "Kanada",
  Mexico: "Mexiko",
  Brazil: "Brazílie",
  Argentina: "Argentina",
  UK: "Spojené království",
  France: "Francie",
  Germany: "Německo",
  Italy: "Itálie",
  Spain: "Španělsko",
  Russia: "Rusko",
  China: "Čína",
  Japan: "Japonsko",
  India: "Indie",
  Australia: "Austrálie",
  NewZealand: "Nový Zéland",
  SouthAfrica: "Jihoafrická republika",
  Egypt: "Egypt",
  Kenya: "Keňa",
  Nigeria: "Nigérie",
  Morocco: "Maroko",
  SaudiArabia: "Saúdská Arábie",
  UAE: "Spojené arabské emiráty",
  Qatar: "Katar",
  Kuwait: "Kuvajt",
  Iraq: "Irák",
  Iran: "Írán",
  Turkey: "Turecko",
  Greece: "Řecko",
  Sweden: "Švédsko",
  Norway: "Norsko",
  Denmark: "Dánsko",
  Finland: "Finsko",
  Iceland: "Island",
  Netherlands: "Nizozemsko",
  Belgium: "Belgie",
  Portugal: "Portugalsko",
  Switzerland: "Švýcarsko",
  Austria: "Rakousko",
  Hungary: "Maďarsko",
  Poland: "Polsko",
  Czechia: "Česko",
  Slovakia: "Slovensko",
  Slovenia: "Slovinsko",
  Croatia: "Chorvatsko",
  BosniaHerzegovina: "Bosna a Hercegovina",
  Serbia: "Srbsko",
  Montenegro: "Černá Hora",
  Albania: "Albánie",
  Kosovo: "Kosovo",
  Macedonia: "Severní Makedonie",
  Bulgaria: "Bulharsko",
  Romania: "Rumunsko",
  Moldova: "Moldavsko",
  Ukraine: "Ukrajina",
  Belarus: "Bělorusko",
  Lithuania: "Litva",
  Latvia: "Lotyšsko",
  Estonia: "Estonsko",
  Armenia: "Arménie",
  Georgia: "Gruzie",
  Azerbaijan: "Ázerbájdžán",
  Kazakhstan: "Kazachstán",
  Uzbekistan: "Uzbekistán",
  Turkmenistan: "Turkmenistán",
  Tajikistan: "Tádžikistán",
  Kyrgyzstan: "Kyrgyzstán",
  Afghanistan: "Afghánistán",
  Pakistan: "Pákistán",
  Bangladesh: "Bangladéš",
  Nepal: "Nepál",
  Bhutan: "Bhútán",
  SriLanka: "Srí Lanka",
  Maldives: "Maledivy",
  Iran: "Írán",
  Lebanon: "Libanon",
  Israel: "Izrael",
  Jordan: "Jordánsko",
  Syria: "Sýrie",
  Palestine: "Palestina",
  Yemen: "Jemen",
  Oman: "Omán",
  Bahrain: "Bahrajn",
  Cyprus: "Kypr",
  Malta: "Malta",
  Mauritius: "Mauricius",
  Madagascar: "Madagaskar",
  Comoros: "Komory",
  CapeVerde: "Kapverdy",
  SaoTomePrincipe: "Svatý Tomáš a Princův ostrov",
  GuineaBissau: "Guinea-Bissau",
  Senegal: "Senegal",
  Gambia: "Gambie",
  Guinea: "Guinea",
  SierraLeone: "Sierra Leone",
  Liberia: "Libérie",
  IvoryCoast: "Pobřeží slonoviny",
  Ghana: "Ghana",
  Togo: "Togo",
  Benin: "Benin",
  Nigeria: "Nigérie",
  Niger: "Niger",
  BurkinaFaso: "Burkina Faso",
  Mali: "Mali",
  Algeria: "Alžírsko",
  Tunisia: "Tunisko",
  Libya: "Libye",
  Sudan: "Súdán",
  SouthSudan: "Jižní Súdán",
  Eritrea: "Eritrea",
  Djibouti: "Džibutsko",
  Somalia: "Somálsko",
  Uganda: "Uganda",
  Rwanda: "Rwanda",
  Burundi: "Burundi",
  Ethiopia: "Etiopie",
  Tanzania: "Tanzanie",
  Kenya: "Keňa",
  Mozambique: "Mosambik",
  Malawi: "Malawi",
  Zambia: "Zambie",
  Zimbabwe: "Zimbabwe",
  Angola: "Angola",
  Namibia: "Namibie",
  Botswana: "Botswana",
  SouthAfrica: "Jihoafrická republika",
  Mauritania: "Mauretánie",
  WesternSahara: "Západní Sahara",
  Morocco: "Maroko",
  Algeria: "Alžírsko",
  Tunisia: "Tunisko",
  Libya: "Libye",
  Egypt: "Egypt",
  Sudan: "Súdán",
  Chad: "Čad",
  Niger: "Niger",
  Mali: "Mali",
  Mauritania: "Mauretánie",
  Senegal: "Senegal",
  Gambia: "Gambie",
  GuineaBissau: "Guinea-Bissau",
  Guinea: "Guinea",
  IvoryCoast: "Pobřeží slonoviny",
  BurkinaFaso: "Burkina Faso",
  Togo: "Togo",
  Benin: "Benin",
  Niger: "Niger",
  Nigeria: "Nigérie",
  Cameroon: "Kamerun",
  EquatorialGuinea: "Rovníková Guinea",
  SãoToméandPríncipe: "Svatý Tomáš a Princův ostrov",
  Gabon: "Gabon",
  Congo: "Kongo",
  DemocraticRepublicCongo: "Demokratická republika Kongo",
  Uganda: "Uganda",
  Kenya: "Keňa",
  SouthSudan: "Jižní Súdán",
  Sudan: "Súdán",
  Rwanda: "Rwanda",
  Burundi: "Burundi",
  Tanzania: "Tanzanie",
  Djibouti: "Džibutsko",
  Somalia: "Somálsko",
  Ethiopia: "Etiopie",
  Eritrea: "Eritrea",
  Comoros: "Komory",
  Mayotte: "Mayotte",
  Madagascar: "Madagaskar",
  Reunion: "Réunion",
  Mauritius: "Mauricius",
  Angola: "Angola",
  Namibia: "Namibie",
  Botswana: "Botswana",
  Zimbabwe: "Zimbabwe",
  Mozambique: "Mosambik",
  Zambia: "Zambie",
  Malawi: "Malawi",
  SouthAfrica: "Jihoafrická republika",
  Lesotho: "Lesotho",
  Swaziland: "Svazijsko",
  Gabon: "Gabon",
  CentralAfricanRepublic: "Středoafrická republika",
  EquatorialGuinea: "Rovníková Guinea",
  SaoTomePrincipe: "Svatý Tomáš a Princův ostrov",
  Cameroon: "Kamerun",
  Chad: "Čad",
  Mauritius: "Mauricius",
  Seychelles: "Seychely",
  CapeVerde: "Kapverdy",
  Bahamas: "Bahamy",
  Haiti: "Haiti",
  DominicanRepublic: "Dominikánská republika",
  Jamaica: "Jamajka",
  TrinidadandTobago: "Trinidad a Tobago",
  Barbados: "Barbados",
  Grenada: "Grenada",
  SaintLucia: "Svatá Lucie",
  SaintVincentandtheGrenadines: "Svatý Vincenc a Grenadiny",
  AntiguaandBarbuda: "Antigua a Barbuda",
  Dominica: "Dominika",
  SaintKittsandNevis: "Svatý Kryštof a Nevis",
  Belize: "Belize",
  ElSalvador: "Salvador",
  CostaRica: "Kostarika",
  Nicaragua: "Nikaragua",
  Honduras: "Honduras",
  Guatemala: "Guatemala",
  Panama: "Panama",
  Colombia: "Kolumbie",
  Venezuela: "Venezuela",
  Guyana: "Guyana",
  Suriname: "Surinam",
  FrenchGuiana: "Francouzská Guyana",
  Brazil: "Brazílie",
  Ecuador: "Ekvádor",
  Peru: "Peru",
  Bolivia: "Bolívie",
  Paraguay: "Paraguay",
  Uruguay: "Uruguay",
  Chile: "Chile",
  Argentina: "Argentina",
  FalklandIslands: "Falklandské ostrovy",
  Australia: "Austrálie",
  NewZealand: "Nový Zéland",
  PapuaNewGuinea: "Papua-Nová Guinea",
  Fiji: "Fidži",
  SolomonIslands: "Šalamounovy ostrovy",
  Vanuatu: "Vanuatu",
  Samoa: "Samoa",
  Tonga: "Tonga",
  Kiribati: "Kiribati",
  Tuvalu: "Tuvalu",
  Nauru: "Nauru",
  MarshallIslands: "Marshallovy ostrovy",
  Palau: "Palau",
  Micronesia: "Mikronésie",
  AmericanSamoa: "Americká Samoa",
  Guam: "Guam",
  NorthernMarianaIslands: "Severní Mariany"
};

module.exports = { Country }