const Country = {
  Afghanistan: "Afghánistán",
  Albania: "Albánie",
  Algeria: "Alžírsko",
  AmericanSamoa: "Americká Samoa",
  Andorra: "Andorra",
  Angola: "Angola",
  Anguilla: "Anguilla",
  Antarctica: "Antarktida",
  AntiguaandBarbuda: "Antigua a Barbuda",
  Argentina: "Argentina",
  Armenia: "Arménie",
  Aruba: "Aruba",
  Australia: "Austrálie",
  Austria: "Rakousko",
  Azerbaijan: "Ázerbájdžán",
  Bahamas: "Bahamy",
  Bahrain: "Bahrajn",
  Bangladesh: "Bangladéš",
  Barbados: "Barbados",
  Belarus: "Bělorusko",
  Belgium: "Belgie",
  Belize: "Belize",
  Benin: "Benin",
  Bermuda: "Bermudy",
  Bhutan: "Bhútán",
  Bolivia: "Bolívie",
  BonaireSintEustatiusandSaba: "Bonaire, Svatý Eustach a Saba",
  BosniaHerzegovina: "Bosna a Hercegovina",
  Botswana: "Botswana",
  BouvetIsland: "Bouvetův ostrov",
  Brazil: "Brazílie",
  BritishIndianOceanTerritory: "Britské indickooceánské území",
  BritishVirginIslands: "Britské Panenské ostrovy",
  Brunei: "Brunej",
  Bulgaria: "Bulharsko",
  BurkinaFaso: "Burkina Faso",
  Burundi: "Burundi",
  CaboVerde: "Kapverdy",
  Cambodia: "Kambodža",
  Cameroon: "Kamerun",
  Canada: "Kanada",
  CaymanIslands: "Kajmanské ostrovy",
  CentralAfricanRepublic: "Středoafrická republika",
  Chad: "Čad",
  Chile: "Chile",
  China: "Čína",
  ChristmasIsland: "Vánoční ostrov",
  CocosKeelingIslands: "Kokosové (Keelingovy) ostrovy",
  Colombia: "Kolumbie",
  Comoros: "Komory",
  Congo: "Kongo",
  CongoDemocraticRepublic: "Demokratická republika Kongo",
  CookIslands: "Cookovy ostrovy",
  CostaRica: "Kostarika",
  Croatia: "Chorvatsko",
  Cuba: "Kuba",
  Curaçao: "Curaçao",
  Cyprus: "Kypr",
  CzechRepublic: "Česká republika",
  Denmark: "Dánsko",
  Djibouti: "Džibutsko",
  Dominica: "Dominika",
  DominicanRepublic: "Dominikánská republika",
  Ecuador: "Ekvádor",
  Egypt: "Egypt",
  ElSalvador: "Salvador",
  EquatorialGuinea: "Rovníková Guinea",
  Eritrea: "Eritrea",
  Estonia: "Estonsko",
  Eswatini: "Eswatini",
  Ethiopia: "Etiopie",
  FalklandIslands: "Falklandské ostrovy",
  FaroeIslands: "Faerské ostrovy",
  Fiji: "Fidži",
  Finland: "Finsko",
  France: "Francie",
  FrenchGuiana: "Francouzská Guyana",
  FrenchPolynesia: "Francouzská Polynésie",
  FrenchSouthernTerritories: "Francouzská jižní území",
  Gabon: "Gabon",
  Gambia: "Gambie",
  Georgia: "Gruzie",
  Germany: "Německo",
  Ghana: "Ghana",
  Gibraltar: "Gibraltar",
  Greece: "Řecko",
  Greenland: "Grónsko",
  Grenada: "Grenada",
  Guadeloupe: "Guadeloupe",
  Guam: "Guam",
  Guatemala: "Guatemala",
  Guernsey: "Guernsey",
  Guinea: "Guinea",
  GuineaBissau: "Guinea-Bissau",
  Guyana: "Guyana",
  Haiti: "Haiti",
  HeardIslandandMcDonaldIslands: "Heardův ostrov a McDonaldovy ostrovy",
  Honduras: "Honduras",
  HongKong: "Hongkong",
  Hungary: "Maďarsko",
  Iceland: "Island",
  India: "Indie",
  Indonesia: "Indonésie",
  Iran: "Írán",
  Iraq: "Irák",
  Ireland: "Irsko",
  IsleofMan: "Ostrov Man",
  Israel: "Izrael",
  Italy: "Itálie",
  IvoryCoast: "Pobřeží slonoviny",
  Jamaica: "Jamajka",
  Japan: "Japonsko",
  Jersey: "Jersey",
  Jordan: "Jordánsko",
  Kazakhstan: "Kazachstán",
  Kenya: "Keňa",
  Kiribati: "Kiribati",
  Kosovo: "Kosovo",
  Kuwait: "Kuvajt",
  Kyrgyzstan: "Kyrgyzstán",
  Laos: "Laos",
  Latvia: "Lotyšsko",
  Lebanon: "Libanon",
  Lesotho: "Lesotho",
  Liberia: "Libérie",
  Libya: "Libye",
  Liechtenstein: "Lichtenštejnsko",
  Lithuania: "Litva",
  Luxembourg: "Lucembursko",
  Macao: "Macao",
  Madagascar: "Madagaskar",
  Malawi: "Malawi",
  Malaysia: "Malajsie",
  Maldives: "Maledivy",
  Mali: "Mali",
  Malta: "Malta",
  MarshallIslands: "Marshallovy ostrovy",
  Martinique: "Martinik",
  Mauritania: "Mauretánie",
  Mauritius: "Mauricius",
  Mayotte: "Mayotte",
  Mexico: "Mexiko",
  Micronesia: "Mikronésie",
  Moldova: "Moldavsko",
  Monaco: "Monako",
  Mongolia: "Mongolsko",
  Montenegro: "Černá Hora",
  Montserrat: "Montserrat",
  Morocco: "Maroko",
  Mozambique: "Mosambik",
  MyanmarBurma: "Myanmar (Barma)",
  Namibia: "Namibie",
  Nauru: "Nauru",
  Nepal: "Nepál",
  Netherlands: "Nizozemsko",
  NewCaledonia: "Nová Kaledonie",
  NewZealand: "Nový Zéland",
  Nicaragua: "Nikaragua",
  Niger: "Niger",
  Nigeria: "Nigérie",
  Niue: "Niue",
  NorfolkIsland: "Norfolk",
  NorthKorea: "Severní Korea",
  NorthMacedonia: "Severní Makedonie",
  NorthernMarianaIslands: "Severní Mariany",
  Norway: "Norsko",
  Oman: "Omán",
  Pakistan: "Pákistán",
  Palau: "Palau",
  Palestine: "Palestina",
  Panama: "Panama",
  PapuaNewGuinea: "Papua-Nová Guinea",
  Paraguay: "Paraguay",
  Peru: "Peru",
  Philippines: "Filipíny",
  PitcairnIslands: "Pitcairnovy ostrovy",
  Poland: "Polsko",
  Portugal: "Portugalsko",
  PuertoRico: "Portoriko",
  Qatar: "Katar",
  Réunion: "Réunion",
  Romania: "Rumunsko",
  Russia: "Rusko",
  Rwanda: "Rwanda",
  SaintBarthélemy: "Svatý Bartoloměj",
  SaintHelena: "Svatá Helena",
  SaintKittsandNevis: "Svatý Kryštof a Nevis",
  SaintLucia: "Svatá Lucie",
  SaintMartin: "Svatý Martin",
  SaintPierreandMiquelon: "Svatý Pierre a Miquelon",
  SaintVincentandtheGrenadines: "Svatý Vincenc a Grenadiny",
  Samoa: "Samoa",
  SanMarino: "San Marino",
  SãoToméandPríncipe: "Svatý Tomáš a Princův ostrov",
  SaudiArabia: "Saúdská Arábie",
  Senegal: "Senegal",
  Serbia: "Srbsko",
  Seychelles: "Seychely",
  SierraLeone: "Sierra Leone",
  Singapore: "Singapur",
  Slovakia: "Slovensko",
  Slovenia: "Slovinsko",
  SolomonIslands: "Šalamounovy ostrovy",
  Somalia: "Somálsko",
  SouthAfrica: "Jihoafrická republika",
  SouthGeorgiaandtheSouthSandwichIslands: "Jižní Georgie a Jižní Sandwichovy ostrovy",
  SouthKorea: "Jižní Korea",
  SouthSudan: "Jižní Súdán",
  Spain: "Španělsko",
  SriLanka: "Srí Lanka",
  Sudan: "Súdán",
  Suriname: "Surinam",
  SvalbardandJanMayen: "Špicberky a Jan Mayen",
  Sweden: "Švédsko",
  Switzerland: "Švýcarsko",
  Syria: "Sýrie",
  Taiwan: "Tchaj-wan",
  Tajikistan: "Tádžikistán",
  Tanzania: "Tanzanie",
  Thailand: "Thajsko",
  TimorLeste: "Východní Timor",
  Togo: "Togo",
  Tokelau: "Tokelau",
  Tonga: "Tonga",
  TrinidadandTobago: "Trinidad a Tobago",
  Tunisia: "Tunisko",
  Turkey: "Turecko",
  Turkmenistan: "Turkmenistán",
  TurksandCaicosIslands: "Turks a Caicos",
  Tuvalu: "Tuvalu",
  Uganda: "Uganda",
  Ukraine: "Ukrajina",
  UAE: "Spojené arabské emiráty",
  UK: "Spojené království",
  Uruguay: "Uruguay",
  Uzbekistan: "Uzbekistán",
  Vanuatu: "Vanuatu",
  VaticanCity: "Vatikán",
  Venezuela: "Venezuela",
  Vietnam: "Vietnam",
  WallisandFutuna: "Wallis a Futuna",
  WesternSahara: "Západní Sahara",
  Yemen: "Jemen",
  Zambia: "Zambie",
  Zimbabwe: "Zimbabwe"
};

module.exports = { Country }